name = "julia_testing_simple_hypotheses"
uuid = "23b92c81-23f6-4c8e-8419-e7448e274eaf"
authors = ["Grant Saggars"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1"
